export const projects = [
  {
      year: "2024",
      project: "Comparative Analysis of Modern Testing Tools: Cypress, Playwright, SerenityJS+Playwright",
      madeAt: "DBS Bank / Singapore Institute of Technology",
      builtWith: ["Node.js", "Cypress", "Playwright", "Serenity/JS", "Selenium"],
  },
  {
      year: "2023",
      project: "LinkedIn Resume Matcher",
      madeAt: "Singapore Institute of Technology",
      builtWith: ["React", "Express", "Node.js", "MongoDB", "HTML", "CSS", "JavaScript", "TypeScript", "Tailwind CSS", "Python", "Pandas", "Flask", "Docker"],
      link: "github.com/Arcadial/resume-matcher",
      linkTitle: "GitHub",
  },
  {
      year: "2023",
      project: "Alexander 'Greek' Thomson Interactive Website",
      madeAt: "University of Glasgow",
      builtWith: ["React", "Express", "Node.js", "MongoDB", "HTML", "CSS", "JavaScript", "Figma", "Illustrator"],
      link: "4b-alexander-thomson-frontend.vercel.app/",
      linkTitle: "4b-alexander-thomson",
  },
  {
      year: "2023",
      project: "Shuttlecock Trajectory Estimation",
      madeAt: "Singapore Institute of Technology",
      builtWith: ["Python", "Machine Learning", "Scikit-learn"],
      link: "github.com/mtwchuang/CSC3005-Shuttlecock-Trajectory-Estimation",
      linkTitle: "GitHub",
  },
  {
      year: "2023",
      project: "Aerial Imagery Analyzer",
      madeAt: "University of Glasgow",
      builtWith: ["Python", "PyAutoGUI", "Selenium", "GeoJSON", "GeoPandas", "Rasterio", "RasterVision", "Docker", "OpenCV", "Machine Learning", "Amazon EC2"],
      link: "drive.google.com/drive/folders/1_xY2aJIOL1tYRucq9DMgq8Wh7gs4p4zz?usp=drive_link",
      linkTitle: "Google Drive",
  },
  {
      year: "2023",
      project: "Binance P2P Tracker",
      builtWith: ["Python", "Pyppeteer"],
      link: "github.com/jfengg3/binance-p2p-tracker",
      linkTitle: "GitHub",
  },
  {
      year: "2022",
      project: "Storyful (AI Transcriber)",
      madeAt: "Glasgow University Tech Society",
      builtWith: ["React", "Express", "Node.js", "Axios", "Bootstrap", "Google Cloud", "AssemblyAI"],
  },
  {
      year: "2022",
      project: "Ridesharing App",
      madeAt: "Singapore Institute of Technology",
      builtWith: ["HTML", "CSS", "Python", "Pandas", "Numpy", "Flask", "OneMapSG API"],
      link: "github.com/aviendre/CSC1008-DSAG-Ridesharing-/",
      linkTitle: "GitHub",
  },
  {
      year: "2021",
      project: "FishBurger (Blog/Posting App)",
      builtWith: ["React", "Express", "Node.js", "MongoDB", "GraphQL"],
  },
  {
      year: "2021",
      project: "MT5 FX Telegram Bot",
      builtWith: ["Python", "MetaTrader5", "Telegram API"],
      link: "github.com/jfengg3/mt5-fx-telebot",
      linkTitle: "GitHub",
  },
  {
      year: "2020",
      project: "Promo Video - Koriya",
      builtWith: ["Premiere Pro"],
      link: "youtu.be/q9zcN-pHyfk",
      linkTitle: "YouTube",
  },
  {
      year: "2019",
      project: "Instana Open House Trail",
      madeAt: "LDR Technology / Republic Polytechnic",
      builtWith: ["Unity 3D", "C#", "HTML5", "Photoshop", "Illustrator"],
      link: "imgur.com/a/b5w4SdZ",
      linkTitle: "Imgur",
  },
  {
      year: "2019",
      project: "Promo Video - FULIFE 5th Incentive Trip Hong Kong",
      madeAt: "FULIFE Pte. Ltd.",
      builtWith: ["Premiere Pro"],
      link: "youtu.be/mKIrxKDSXpY",
      linkTitle: "YouTube",
  },
  {
      year: "2018",
      project: "Promo Video - HOREX Crypto",
      madeAt: "FULIFE Pte. Ltd.",
      builtWith: ["Premiere Pro", "After Effects", "Photoshop"],
      link: "youtu.be/VhGhIhjZt8k",
      linkTitle: "YouTube",
  },
  {
      year: "2018",
      project: "Swatch - White Rebel 3D Advertisement",
      madeAt: "Republic Polytechnic",
      builtWith: ["Maya", "Mental Ray", "Photoshop", "Sony Vegas"],
      link: "youtu.be/ur7rMAvH8UU",
      linkTitle: "YouTube",
  },
  {
      year: "2018",
      project: "RP Exam Downloader",
      madeAt: "Republic Polytechnic",
      builtWith: ["Python"],
      link: "github.com/jfengg3/rp-exam-downloader",
      linkTitle: "GitHub",
  },
  {
      year: "2018",
      project: "RP Student Intake Visualization Dashboard",
      madeAt: "Republic Polytechnic",
      builtWith: ["Python", "Dash", "Plotly.js", "React", "Flask"],
      link: "github.com/jfengg3/rp-student-intake-viz",
      linkTitle: "GitHub",
  },
  {
      year: "2017",
      project: "Sycro",
      builtWith: ["Visual Studio", "C#", "Bunifu UI"],
      link: "github.com/jfengg3/Sycro",
      linkTitle: "GitHub",
  },
];